[tool.poetry]
name = "hyde"
version = "0.0.1"
description = "Retrieval with Hypothetical Document Embeddings (HyDE)"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
openai = "<2"
chromadb = "^0.4.15"
tiktoken = "^0.5.1"
langchain-text-splitters = ">=0.0.1,<0.1"

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.24.1"
langchain-cli = ">=0.0.21"
fastapi = ">=0.104.0,<1"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "hyde.chain"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["OpenAI", "ChromaDB"]
tags = ["paper"]

[tool.poe.tasks.start]
cmd = "uvicorn langchain_cli.dev_scripts:create_demo_server --reload --port $port --host $host"
args = [
    { name = "port", help = "port to run on", default = "8000" },
    { name = "host", help = "host to run on", default = "127.0.0.1" },
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
